name = "deepseek-v3-di"
release_date = "2025-02-17"
last_updated = "2025-02-17"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = 64_000
output = null

[modalities]
input = ["text"]
output = ["text"]
