name = "DeepSeek-V3-DI"
release_date = "2025-02-17"
last_updated = "2025-02-17"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 64_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
