name = "L31 70B Euryale V2.2"
release_date = "2026-01"
last_updated = "2026-01"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = false
open_weights = true

[cost]
input = 1.48
output = 1.48

[limit]
context = 8192
output = 8192

[modalities]
input = ["text"]
output = ["text"]
