name = "DeepSeek R1 0528"
family = "deepseek-r1"
attachment = false
reasoning = true
tool_call = false
structured_output = true
temperature = true
release_date = "2025-07-11"
last_updated = "2025-12-23"
open_weights = true

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
