name = "Gemini 2.5 Pro"
family = "gemini-pro"

release_date = "2025-03-20"
last_updated = "2026-03-03"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false
knowledge = "2025-01"

[cost]
input = 1.25
output = 10
cache_read = 0.125
cache_write = 0.375

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["text", "image", "pdf", "audio", "video"]
output = ["text"]
