name = "Gemini 2.5 Flash Lite Preview 09-25"
family = "gemini-flash-lite"

release_date = "2025-09-25"
last_updated = "2026-03-03"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false
knowledge = "2025-01"

[cost]
input = 0.1
output = 0.4
cache_read = 0.01
cache_write = 0.083333

[limit]
context = 1_048_576
output = 65_536

[modalities]
input = ["text", "image", "pdf", "audio", "video"]
output = ["text"]
