name = "Z.AI GLM-4.7"
release_date = "1970-01-01"
last_updated = "1970-01-01"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0
output = 0

[limit]
context = 131_072
output = 40_000

[modalities]
input = ["text"]
output = ["text"]
