name = "gemma-3-27b"
release_date = "2025-03-17"
last_updated = "2025-03-17"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = null
output = null

[modalities]
input = ["text"]
output = ["text"]
