name = "Perplexity-Sonar"
release_date = "2025-01-25"
last_updated = "2025-01-25"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[limit]
context = 127_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
