name = "codestral latest"
release_date = "2024-10-08"
last_updated = "2024-10-08"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = -6999956
output = -6999896

[limit]
context = 128000
output = 16384

[modalities]
input = ["text"]
output = ["text"]
