name = "Qwen: Qwen-Plus"

release_date = "2025-02-01"
last_updated = "2026-03-03"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.4
output = 1.2
cache_read = 0.08

[limit]
context = 1_000_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
