id = "qwen/qwen2.5-vl-72b-instruct:free"
name = "Qwen2.5 VL 72B Instruct"
family = "qwen"

release_date = "2025-02-01"
last_updated = "2026-03-03"
attachment = true
reasoning = false
temperature = true
tool_call = false
structured_output = true
open_weights = true
knowledge = "2024-10"

[cost]
input = 0.8
output = 0.8

[limit]
context = 32_768
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
