# TODO: Fill in model details
# Model ID: openrouter/qwen/qwen3-30b-a3b:free

name = "qwen3 30u a3u:free"
release_date = "2025-12-07"
last_updated = "2025-12-07"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
