# TODO: Fill in model details
# Model ID: openrouter/lizpreciatior/lzlv-70b-fp16-hf

name = "lzlv 70u fp16 hf"
release_date = "2025-12-07"
last_updated = "2025-12-07"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
