name = "MiniMax M2"
family = "minimaxai"
release_date = "2025-12-29"
last_updated = "2025-12-29"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.26
output = 1.02
reasoning = 1.53
cache_read = 0.0
cache_write = 0.0
input_audio = 0.0
output_audio = 0.0

[limit]
context = 196608
output = 196608

[modalities]
input = ['text']
output = ['text']

[interleaved]
field = "reasoning_content"
