name = "Qwen3 Next 80B A3B Thinking"
family = "qwen3"
release_date = "2025-09-12"
last_updated = "2025-09-12"
attachment = false
reasoning = true
temperature = true
knowledge = "2025-09"
tool_call = true
open_weights = true

[cost]
input = 0.5
output = 6.0

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
