name = "DeepSeek R1 (0528)"
release_date = "2025-05-28"
last_updated = "2025-05-28"
attachment = true
reasoning = true
temperature = true
knowledge = "2024-07"
tool_call = true
open_weights = false

[cost]
input = 0.3
output = 0.045

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]