name = "Kimi K2 Instruct 0905 (exacto)"
family = "kimi"

release_date = "2025-09-05"
last_updated = "2026-03-03"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = true
knowledge = "2024-10"

[cost]
input = 0.6
output = 2.5

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
