name = "Qwen3 30B A3B"
family = "qwen3"
attachment = false
reasoning = true
tool_call = true
structured_output = true
temperature = true
release_date = "2025-06-16"
last_updated = "2025-12-23"
open_weights = true

[limit]
context = 131_072
output = 8_000

[modalities]
input = ["text"]
output = ["text"]
