name = "gpt-researcher"
release_date = "2025-01-03"
last_updated = "2025-01-03"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = null
output = null

[modalities]
input = ["text"]
output = ["text"]
