name = "GPT-Researcher"
release_date = "2025-01-03"
last_updated = "2025-01-03"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
