name = "mistral-medium"
release_date = "2023-12-20"
last_updated = "2023-12-20"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[cost]
input = 2.7
output = 8.1

[limit]
context = 128_000
output = null

[modalities]
input = ["text", "image"]
output = ["text"]
