name = "flux-schnell"
release_date = "2024-08-01"
last_updated = "2024-08-01"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = 256
output = null

[modalities]
input = ["text", "image"]
output = ["image"]
