name = "Hailuo-AI"
release_date = "2024-10-17"
last_updated = "2024-10-17"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["video"]
