name = "hailuo-02-standard"
release_date = "2025-06-18"
last_updated = "2025-06-18"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = null
output = null

[modalities]
input = ["text"]
output = ["video"]
