name = "Kling-1.5-Pro"
release_date = "2024-12-04"
last_updated = "2024-12-04"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[limit]
context = 0
output = 0

[modalities]
input = ["text", "image"]
output = ["video"]
