name = "veo-3-vfast"
release_date = "2025-07-10"
last_updated = "2025-07-10"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = null
output = null

[modalities]
input = ["text"]
output = ["video"]
