name = "claude-3-haiku-20240307"
family = "claude-haiku"
release_date = "2026-01"
last_updated = "2026-01"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.225
output = 1.125

[limit]
context = 200000
output = 4096

[modalities]
input = ["text", "image"]
output = ["text"]
