name = "gpt-4.1-mini"
family = "gpt"
release_date = "2026-01"
last_updated = "2026-01"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.36
output = 1.44

[limit]
context = 1047576
output = 32768

[modalities]
input = ["text", "image"]
output = ["text"]
