name = "GLM 4.6V"
family = "glm"
attachment = true
reasoning = false
tool_call = true
structured_output = true
temperature = true
release_date = "2025-12-11"
last_updated = "2025-12-29"
open_weights = true

[cost]
input = 0.39
output = 1.13

[limit]
context = 131_072
output = 32_768

[modalities]
input = ["text", "image"]
output = ["text"]
