name = "Mistral: Mistral Large 3 2512"

release_date = "2025-12-01"
last_updated = "2026-03-03"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.5
output = 1.5

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text", "image"]
output = ["text"]
