id = "mistralai/mistral-small-3.2-24b-instruct:free"
name = "Mistral Small 3.2 24B Instruct"
family = "mistral-small"

release_date = "2025-06-20"
last_updated = "2026-03-03"
attachment = true
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = true
knowledge = "2024-10"

[cost]
input = 0.06
output = 0.18
cache_read = 0.03

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["image", "text"]
output = ["text"]
