name = "deepseek-r1"
release_date = "2025-01-22"
last_updated = "2025-01-22"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = 160_000
output = null

[modalities]
input = ["text", "image"]
output = ["text"]
