name = "DeepSeek-V3"
release_date = "2025-01-04"
last_updated = "2025-01-04"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 160_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
