name = "flux-pro-1.1-t"
release_date = "2024-11-06"
last_updated = "2024-11-06"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = 256
output = null

[modalities]
input = ["text", "image"]
output = ["image"]
