name = "glm-4.5-air-t"
release_date = "2025-08-08"
last_updated = "2025-08-08"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = null
output = null

[modalities]
input = ["text"]
output = ["text"]
