name = "gpt-oss-120b-t"
release_date = "2025-08-05"
last_updated = "2025-08-05"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = 128_000
output = null

[modalities]
input = ["text", "image"]
output = ["text"]
