name = "qwen-2.5-72b-t"
release_date = "2024-11-06"
last_updated = "2024-11-06"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = 32_768
output = null

[modalities]
input = ["text"]
output = ["text"]
