name = "Qwen-3-235B-2507-T"
release_date = "2025-04-30"
last_updated = "2025-04-30"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 40_960
output = 0

[modalities]
input = ["text", "image"]
output = ["text"]
