name = "ZAI-GLM-4.6-CS"
release_date = "2025-11-11"
last_updated = "2025-11-11"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = false

[limit]
context = 131_000
output = 40_000

[modalities]
input = ["text", "image"]
output = ["text"]
