name = "Solar-Pro-2"
release_date = "2023-09-13"
last_updated = "2023-09-13"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 4_096
output = 1_024

[modalities]
input = ["text", "image"]
output = ["text"]
