name = "Seedance-1.0-Pro-Fast"
release_date = "2025-10-24"
last_updated = "2025-10-24"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 0
output = 0

[modalities]
input = ["text", "image"]
output = ["video"]
