name = "Aya-Expanse-32B"
release_date = "2025-02-18"
last_updated = "2025-02-18"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
