name = "Command-R"
release_date = "2024-03-21"
last_updated = "2024-03-21"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 128_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
