name = "indictrans2 en indic 1B"
release_date = "2025-09-25"
last_updated = "2025-09-25"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = -6999996.46
output = -6999996.46

[limit]
context = 128000
output = 16384

[modalities]
input = ["text"]
output = ["text"]
