name = "Llama 3.2 11B Vision Instruct"
family = "llama-3.2"
release_date = "2025-08-23"
last_updated = "2025-08-23"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 49000
output = 680000

[limit]
context = 128000
output = 16384

[modalities]
input = ["text"]
output = ["text"]
