name = "llama 3.2 11u vision instruct"
release_date = "2025-04-03"
last_updated = "2025-04-03"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = -7999994.96
output = -6999993.06

[limit]
context = 128000
output = 16384

[modalities]
input = ["text"]
output = ["text"]
