name = "deepseek-v3-fw"
release_date = "2024-12-31"
last_updated = "2024-12-31"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = 160_000
output = null

[modalities]
input = ["text"]
output = ["text"]
