name = "Deepseek-V3-FW"
release_date = "2024-12-31"
last_updated = "2024-12-31"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 160_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
