name = "flux-1-schnell-fw"
release_date = "2024-10-22"
last_updated = "2024-10-22"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = 256
output = null

[modalities]
input = ["text"]
output = ["image"]
