name = "Llama-3.3-70B-FW"
release_date = "2024-12-06"
last_updated = "2024-12-06"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[limit]
context = 128_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
