name = "Llama-3.1-8B-FW"
release_date = "2024-07-23"
last_updated = "2024-07-23"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 128_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
