name = "Qwen3-Coder"
release_date = "2025-07-23"
last_updated = "2025-07-23"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
