name = "Qwen3-235B-2507-FW"
release_date = "2025-04-29"
last_updated = "2025-04-29"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 100_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
