name = "Qwen-2.5-VL-32b"
release_date = "2025-04-01"
last_updated = "2025-04-01"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[limit]
context = 32_768
output = 0

[modalities]
input = ["text"]
output = ["text"]
