name = "deepseek-v3.1-tm"
release_date = "2025-09-22"
last_updated = "2025-09-22"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = null
output = null

[modalities]
input = ["text"]
output = ["text"]
