name = "glm-4.5"
release_date = "2025-07-31"
last_updated = "2025-07-31"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = null
output = null

[modalities]
input = ["text"]
output = ["text"]
