name = "Kimi-K2-Thinking"
release_date = "2025-11-07"
last_updated = "2025-11-07"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
