name = "qwen3-vl-235b-a22b-t"
release_date = "2025-09-24"
last_updated = "2025-09-24"
attachment = true
reasoning = null
temperature = false
open_weights = false
tool_call = null

[limit]
context = null
output = null

[modalities]
input = ["text"]
output = ["text"]
