# TODO: Fill in model details
# Model ID: google-vertex-ai/gemini-2.5-pro-preview-05-06

name = "gemini 2.5 pro preview 05 06"
release_date = "2025-12-07"
last_updated = "2025-12-07"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
