name = "Phoenix-1.0"
release_date = "2025-05-30"
last_updated = "2025-05-30"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["image"]
