# TODO: Fill in model details
# Model ID: openrouter/baidu/ernie-4.5-vl-28b-a3b

name = "ernie 4.5 vl 28u a3b"
release_date = "2025-12-07"
last_updated = "2025-12-07"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[limit]
context = 0
output = 0

[modalities]
input = ["text"]
output = ["text"]
