name = "Llama-3.1-70B-FP16"
release_date = "2024-08-19"
last_updated = "2024-08-19"
attachment = true
reasoning = false
temperature = false
open_weights = false
tool_call = false
[limit]
context = 131_000
output = 0

[modalities]
input = ["text"]
output = ["text"]
