# https://developers.cloudflare.com/workers-ai/models/dreamshaper-8-lcm/

name = "@cf/lykon/dreamshaper-8-lcm"
attachment = true
reasoning = false
tool_call = false
temperature = false
open_weights = true
release_date = "2024-02-27"
last_updated = "todo"

[cost]
input = 0
output = 0

[modalities]
input = ["text"]
output = ["image"]
