# https://developers.cloudflare.com/workers-ai/models/falcon-7b-instruct/

name = "@cf/tiiuae/falcon-7b-instruct"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
release_date = "2024-02-27"
last_updated = "todo"

[cost]
input = 0
output = 0

[limit]
context = 4096

[modalities]
input = ["text"]
output = ["text"]
