name = "GPT-5.1-Codex-Mini"
family = "gpt-codex"

release_date = "2025-11-13"
last_updated = "2026-03-03"
attachment = true
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = false
knowledge = "2024-09-30"

[cost]
input = 0.25
output = 2
cache_read = 0.025

[limit]
context = 400_000
output = 100_000

[modalities]
input = ["image", "text"]
output = ["text"]
