name = "meta llama 3 8u instruct"
release_date = "2025-02-05"
last_updated = "2025-02-05"
attachment = false
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = -7999994.99999999999999946
output = -6999997.36

[limit]
context = 128000
output = 16384

[modalities]
input = ["text"]
output = ["text"]
