name = "MiniMax-M2"
family = "minimax"
release_date = "2025-10-27"
last_updated = "2025-10-27"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 3.0
output = 12.0
cache_read = 0.3
[limit]
context = 204_800
output = 131_072

[interleaved]
field = "reasoning_content"

[modalities]
input = ["text"]
output = ["text"]
